function cmdUsed(sh, prefix) {
  const since = sh.game?.taskStartIdx ?? 0;
  return sh.history.slice(since).some(h => h.trim().startsWith(prefix));
}
function fileExists(fs, path) { return fs.get(path) !== null; }
function fileContains(fs, path, text) {
  const [ok, c] = fs.read(path);
  return ok && c.includes(text);
}
function permIs(fs, fname, perm) {
  for (const p of [`/home/user/${fname}`, `/home/user/projects/${fname}`, `/tmp/${fname}`]) {
    const n = fs.get(p);
    if (n && n.perms === perm) return true;
  }
  return false;
}
function fileAnywhere(fs, fname) {
  for (const dir of ["/home/user", "/home/user/projects", "/home/user/project", "/tmp"]) {
    if (fs.get(`${dir}/${fname}`)) return true;
  }
  return false;
}
function fileContainsAnywhere(fs, fname, text) {
  for (const dir of ["/home/user", "/home/user/projects", "/home/user/project", "/tmp"]) {
    const node = fs.get(`${dir}/${fname}`);
    if (node && !node.isDir && node.content.includes(text)) return true;
  }
  return false;
}

const LEVELS = [
  { name: "Миссия 1: Знакомство", desc: "Основы: кто я, где я",
    tasks: [
      { title: "Кто ты?",
        desc: "Узнай текущего пользователя с помощью команды `whoami`",
        hint: "whoami",
        check: sh => cmdUsed(sh, "whoami") },
      { title: "Где ты?",
        desc: "Выполни `pwd` — она покажет текущую директорию.",
        hint: "pwd",
        check: sh => cmdUsed(sh, "pwd") },
      { title: "Что вокруг?",
        desc: "Посмотри содержимое текущей папки командой `ls`",
        hint: "ls",
        check: sh => cmdUsed(sh, "ls") },
      { title: "Что за ОС?",
        desc: "Выполни `uname -a`, чтобы узнать информацию о системе.",
        hint: "uname -a",
        check: sh => cmdUsed(sh, "uname -a") },
    ]},

  { name: "Миссия 2: Навигация", desc: "Путешествие по FS",
    tasks: [
      { title: "Перейти в /etc",
        desc: "Перейди в системный каталог командой `cd /etc`",
        hint: "cd /etc",
        check: sh => sh.fs.cwd === "/etc" },
      { title: "Домой",
        desc: "Вернись в домашний каталог: `cd ~`",
        hint: "cd ~",
        check: sh => sh.fs.cwd === "/home/user" },
      { title: "В /var/log",
        desc: "Перейди в `/var/log` и посмотри содержимое через `ls`.",
        hint: "cd /var/log && ls",
        check: sh => sh.fs.cwd === "/var/log" && cmdUsed(sh, "ls") },
      { title: "Читаем syslog",
        desc: "Прочитай файл `syslog` командой `cat syslog`.",
        hint: "cat syslog",
        check: sh => cmdUsed(sh, "cat syslog") },
    ]},

  { name: "Миссия 3: Файлы", desc: "Создание и управление",
    tasks: [
      { title: "Создать каталог",
        desc: "Создай каталог командой `mkdir ~/projects`",
        hint: "mkdir ~/projects",
        check: sh => fileAnywhere(sh.fs, "projects") || !!sh.fs.get("/home/user/projects") },
      { title: "Создать файл",
        desc: "Перейди в `~/projects` и создай файл: `touch notes.txt`",
        hint: "cd ~/projects && touch notes.txt",
        check: sh => fileAnywhere(sh.fs, "notes.txt") },
      { title: "Записать текст",
        desc: "Запиши в файл строку: `echo 'Hello Linux' > notes.txt`",
        hint: "echo Hello Linux > notes.txt",
        check: sh => fileContainsAnywhere(sh.fs, "notes.txt", "Hello") },
      { title: "Скопировать",
        desc: "Скопируй файл: `cp notes.txt backup.txt`",
        hint: "cp notes.txt backup.txt",
        check: sh => fileAnywhere(sh.fs, "backup.txt") },
      { title: "Переименовать",
        desc: "Переименуй: `mv backup.txt copy.txt`",
        hint: "mv backup.txt copy.txt",
        check: sh => fileAnywhere(sh.fs, "copy.txt") },
      { title: "Удалить",
        desc: "Удали файл: `rm copy.txt`",
        hint: "rm copy.txt",
        check: sh => !fileAnywhere(sh.fs, "copy.txt") },
    ]},

  { name: "Миссия 4: Текст", desc: "grep, sort, wc, head, tail",
    tasks: [
      { title: "grep",
        desc: "Найди строку `apple` в файле `~/data.txt`: `grep apple data.txt`",
        hint: "grep apple data.txt",
        check: sh => cmdUsed(sh, "grep") && sh.history.some(h => h.includes("apple")) },
      { title: "head",
        desc: "Покажи первую строку: `head -n 1 data.txt`",
        hint: "head -n 1 data.txt",
        check: sh => cmdUsed(sh, "head") },
      { title: "tail",
        desc: "Покажи последние 2 строки: `tail -n 2 data.txt`",
        hint: "tail -n 2 data.txt",
        check: sh => cmdUsed(sh, "tail") },
      { title: "wc",
        desc: "Посчитай строки: `wc -l data.txt`",
        hint: "wc -l data.txt",
        check: sh => cmdUsed(sh, "wc") },
      { title: "sort",
        desc: "Отсортируй файл: `sort data.txt`",
        hint: "sort data.txt",
        check: sh => cmdUsed(sh, "sort") },
      { title: "uniq",
        desc: "Убери дубликаты: `uniq data.txt`",
        hint: "uniq data.txt",
        check: sh => cmdUsed(sh, "uniq") },
    ]},

  { name: "Миссия 5: Права", desc: "chmod, chown",
    tasks: [
      { title: "Создать каталог",
        desc: "Создай каталог `~/projects` (с буквой 's'): `mkdir ~/projects`",
        hint: "mkdir ~/projects",
        check: sh => !!sh.fs.get("/home/user/projects") },
      { title: "Смотри права",
        desc: "Посмотри права файлов командой `ls -l`",
        hint: "ls -l",
        check: sh => cmdUsed(sh, "ls -l") },
      { title: "Исполняемый",
        desc: "Создай `script.sh` и дай права: `chmod 755 script.sh`",
        hint: "touch script.sh && chmod 755 script.sh",
        check: sh => permIs(sh.fs, "script.sh", "rwxr-xr-x") },
      { title: "Только чтение",
        desc: "Установи права `644` для `data.txt`: `chmod 644 data.txt`",
        hint: "chmod 644 data.txt",
        check: sh => permIs(sh.fs, "data.txt", "rw-r--r--") },
      { title: "chown",
        desc: "Смени владельца: `chown root data.txt`",
        hint: "chown root data.txt",
        check: sh => { const n = sh.fs.get("/home/user/data.txt"); return n && n.owner === "root"; } },
    ]},

  { name: "Миссия 6: Процессы", desc: "ps, kill, df, free",
    tasks: [
      { title: "ps",
        desc: "Покажи список процессов: `ps`",
        hint: "ps", check: sh => cmdUsed(sh, "ps") },
      { title: "df",
        desc: "Узнай место на диске: `df`",
        hint: "df", check: sh => cmdUsed(sh, "df") },
      { title: "free",
        desc: "Проверь память: `free`",
        hint: "free", check: sh => cmdUsed(sh, "free") },
      { title: "uptime",
        desc: "Узнай аптайм системы: `uptime`",
        hint: "uptime", check: sh => cmdUsed(sh, "uptime") },
      { title: "id",
        desc: "Покажи свой uid/gid: `id`",
        hint: "id", check: sh => cmdUsed(sh, "id") },
    ]},

  { name: "Миссия 7: Пайпы", desc: "| > >> ;",
    tasks: [
      { title: "Пайп",
        desc: "Используй конвейер: `grep o /etc/passwd | wc -l`",
        hint: "grep o /etc/passwd | wc -l",
        check: sh => sh.history.some(h => h.includes("|") && h.includes("grep") && h.includes("wc")) },
      { title: "Редирект >",
        desc: "Сохрани вывод в файл: `ls -l > ~/listing.txt`",
        hint: "ls -l > ~/listing.txt",
        check: sh => fileExists(sh.fs, "/home/user/listing.txt") },
      { title: "Дозапись >>",
        desc: "Допиши строку: `echo end >> ~/listing.txt`",
        hint: "echo end >> ~/listing.txt",
        check: sh => fileContains(sh.fs, "/home/user/listing.txt", "end") },
      { title: "Цепочка ;",
        desc: "Выполни две команды: `cd /tmp; ls`",
        hint: "cd /tmp; ls",
        check: sh => sh.history.some(h => h.includes(";")) },
    ]},

  { name: "Миссия 8: Продвинутое", desc: "awk, sed, find",
    tasks: [
      { title: "awk",
        desc: "Выведи второе поле: `awk '{print $2}' /etc/passwd`",
        hint: "awk '{print $2}' /etc/passwd",
        check: sh => cmdUsed(sh, "awk") },
      { title: "sed",
        desc: "Замени текст: `sed 's/apple/orange/g' data.txt`",
        hint: "sed 's/apple/orange/g' data.txt",
        check: sh => cmdUsed(sh, "sed") },
      { title: "find",
        desc: "Найди все `.txt`: `find /home/user -name '*.txt'`",
        hint: "find /home/user -name '*.txt'",
        check: sh => sh.history.some(h => h.includes("find") && h.includes("*.txt")) },
      { title: "alias",
        desc: "Создай алиас: `alias ll='ls -l'`",
        hint: "alias ll='ls -l'",
        check: sh => "ll" in sh.aliases },
      { title: "export",
        desc: "Установи переменную: `export MYVAR=hello`",
        hint: "export MYVAR=hello",
        check: sh => sh.env.MYVAR === "hello" },
      { title: "history",
        desc: "Посмотри историю команд: `history`",
        hint: "history", check: sh => cmdUsed(sh, "history") },
    ]},

  { name: "Миссия 9: Vim", desc: "Редактор",
    tasks: [
      { title: "Открыть vim",
        desc: "Создай файл через vim: `vim hello.txt`",
        hint: "vim hello.txt",
        check: sh => fileExists(sh.fs, "/home/user/hello.txt") || fileExists(sh.fs, "/home/user/projects/hello.txt") },
      { title: "Содержимое",
        desc: "Запиши в файл текст `Hello Vim!` (Esc для выхода)",
        hint: "vim hello.txt → введи → Esc",
        check: sh => fileContains(sh.fs, "/home/user/hello.txt", "Hello") ||
                     fileContains(sh.fs, "/home/user/projects/hello.txt", "Hello") },
    ]},

  { name: "Миссия 10: Bash-скрипты", desc: "Переменные, циклы, условия",
    tasks: [
      { title: "Скрипт",
        desc: "Создай `script.sh` с командой `echo`",
        hint: "vim script.sh",
        check: sh => ["/home/user/script.sh", "/home/user/projects/script.sh"].some(p => fileContains(sh.fs, p, "echo")) },
      { title: "Цикл",
        desc: "Напиши цикл: `for i in 1 2 3; do echo $i; done`",
        hint: "for i in 1 2 3; do echo $i; done",
        check: sh => sh.history.some(h => h.includes("for") && h.includes("do")) },
      { title: "Условие",
        desc: "Проверь: `if [ -f /etc/passwd ]; then echo yes; fi`",
        hint: "if [ -f /etc/passwd ]; then echo yes; fi",
        check: sh => sh.history.some(h => h.includes("if") && h.includes("then")) },
      { title: "Переменная",
        desc: "Установи переменную: `NAME=Linux; echo $NAME`",
        hint: "NAME=Linux; echo $NAME",
        check: sh => sh.history.some(h => h.match(/^\w+=/)) },
    ]},

  { name: "Миссия 11: Сети", desc: "ip, ping, ss, curl",
    tasks: [
      { title: "IP",
        desc: "Посмотри IP-адреса: `ip a`",
        hint: "ip a", check: sh => cmdUsed(sh, "ip") },
      { title: "Маршруты",
        desc: "Покажи таблицу маршрутов: `ip r`",
        hint: "ip r", check: sh => sh.history.some(h => h.includes("ip r")) },
      { title: "Ping",
        desc: "Проверь связь с хостом: `ping example.com`",
        hint: "ping example.com", check: sh => cmdUsed(sh, "ping") },
      { title: "Порты",
        desc: "Посмотри открытые порты: `ss`",
        hint: "ss", check: sh => cmdUsed(sh, "ss") || cmdUsed(sh, "netstat") },
      { title: "curl",
        desc: "Сделай HTTP-запрос: `curl http://example.com`",
        hint: "curl http://example.com",
        check: sh => cmdUsed(sh, "curl") },
    ]},

  { name: "Миссия 12: Systemd", desc: "Управление сервисами",
    tasks: [
      { title: "Список юнитов",
        desc: "Покажи все сервисы: `systemctl list-units`",
        hint: "systemctl list-units",
        check: sh => sh.history.some(h => h.includes("list-units")) },
      { title: "Статус",
        desc: "Проверь статус сервиса: `systemctl status myapp`",
        hint: "systemctl status myapp",
        check: sh => sh.history.some(h => h.includes("status")) },
      { title: "Включить",
        desc: "Включи автозапуск: `systemctl enable myapp`",
        hint: "systemctl enable myapp",
        check: sh => sh.history.some(h => h.includes("enable")) },
      { title: "Логи",
        desc: "Посмотри логи системы: `journalctl`",
        hint: "journalctl",
        check: sh => cmdUsed(sh, "journalctl") },
    ]},

  { name: "Миссия 13: Пакеты", desc: "apt, dpkg",
    tasks: [
      { title: "Обновление",
        desc: "Обнови индексы пакетов: `sudo apt update`",
        hint: "sudo apt update",
        check: sh => sh.history.some(h => h.includes("apt update")) },
      { title: "Установка",
        desc: "Установи пакет: `sudo apt install nginx`",
        hint: "sudo apt install nginx",
        check: sh => sh.history.some(h => h.includes("apt install")) },
      { title: "Удаление",
        desc: "Удали пакет: `sudo apt remove nginx`",
        hint: "sudo apt remove nginx",
        check: sh => sh.history.some(h => h.includes("apt remove")) },
      { title: "Список",
        desc: "Покажи установленные пакеты: `dpkg -l`",
        hint: "dpkg -l", check: sh => cmdUsed(sh, "dpkg") },
    ]},

  { name: "Миссия 14: Архивы", desc: "tar, gzip, zip",
    tasks: [
      { title: "tar создать",
        desc: "Создай архив: `tar -cf archive.tar /home/user`",
        hint: "tar -cf archive.tar /home/user",
        check: sh => cmdUsed(sh, "tar") },
      { title: "tar распаковать",
        desc: "Распакуй архив: `tar -xf archive.tar`",
        hint: "tar -xf archive.tar",
        check: sh => sh.history.some(h => h.includes("tar") && h.includes("-xf")) },
      { title: "gzip",
        desc: "Сожми файл: `gzip file.txt`",
        hint: "gzip file.txt", check: sh => cmdUsed(sh, "gzip") },
      { title: "zip",
        desc: "Создай zip-архив: `zip arch.zip file.txt`",
        hint: "zip arch.zip file.txt", check: sh => cmdUsed(sh, "zip") },
    ]},

  { name: "Миссия 15: Мастер", desc: "Финальные испытания",
    tasks: [
      { title: "Комбо 1",
        desc: "Найди строки с `user`: `grep user /etc/passwd`",
        hint: "grep user /etc/passwd",
        check: sh => sh.history.some(h => h.includes("grep user") && h.includes("passwd")) },
      { title: "Комбо 2",
        desc: "Сохрани отсортированный passwd: `sort /etc/passwd > users.txt`",
        hint: "sort /etc/passwd > users.txt",
        check: sh => fileExists(sh.fs, "/home/user/users.txt") || fileExists(sh.fs, "/home/user/projects/users.txt") },
      { title: "Комбо 3",
        desc: "Посчитай строки: `wc -l users.txt`",
        hint: "wc -l users.txt",
        check: sh => sh.history.some(h => h.includes("wc") && h.includes("users.txt")) },
      { title: "Комбо 4",
        desc: "Создай `backup.sh` с командой `tar`",
        hint: "vim backup.sh",
        check: sh => ["/home/user/backup.sh", "/home/user/projects/backup.sh"].some(p => fileContains(sh.fs, p, "tar")) },
      { title: "Комбо 5",
        desc: "Дай права на исполнение: `chmod 755 backup.sh`",
        hint: "chmod 755 backup.sh",
        check: sh => permIs(sh.fs, "backup.sh", "rwxr-xr-x") },
    ]},

  { name: "Миссия 16: Диагностика", desc: "top, lsof, dmesg",
    tasks: [
      { title: "top",
        desc: "Запусти мониторинг: `top`",
        hint: "top", check: sh => cmdUsed(sh, "top") },
      { title: "htop",
        desc: "Улучшенный мониторинг: `htop`",
        hint: "htop", check: sh => cmdUsed(sh, "htop") },
      { title: "lsof",
        desc: "Какие файлы открыты: `lsof`",
        hint: "lsof", check: sh => cmdUsed(sh, "lsof") },
      { title: "dmesg",
        desc: "Логи ядра: `dmesg`",
        hint: "dmesg", check: sh => cmdUsed(sh, "dmesg") },
      { title: "strace",
        desc: "Трассировка: `strace ls`",
        hint: "strace ls", check: sh => cmdUsed(sh, "strace") },
    ]},

  { name: "Миссия 17: Пользователи", desc: "useradd, passwd",
    tasks: [
      { title: "passwd файл",
        desc: "Посмотри список пользователей: `cat /etc/passwd`",
        hint: "cat /etc/passwd",
        check: sh => sh.history.some(h => h.includes("cat /etc/passwd")) },
      { title: "Группы",
        desc: "Узнай свои группы: `groups`",
        hint: "groups", check: sh => cmdUsed(sh, "groups") },
      { title: "useradd",
        desc: "Добавь пользователя: `sudo useradd testuser`",
        hint: "sudo useradd testuser",
        check: sh => sh.history.some(h => h.includes("useradd")) },
      { title: "passwd",
        desc: "Смени пароль: `sudo passwd testuser`",
        hint: "sudo passwd testuser",
        check: sh => sh.history.some(h => h.includes("passwd")) },
    ]},

  { name: "Миссия 18: Linux Operator", desc: "Финальная",
    tasks: [
      { title: "Логи",
        desc: "Найди все `.log`: `find /var/log -name '*.log'`",
        hint: "find /var/log -name '*.log'",
        check: sh => sh.history.some(h => h.includes("find /var/log")) },
      { title: "Порты",
        desc: "Покажи слушающие порты: `ss -tuln`",
        hint: "ss -tuln",
        check: sh => sh.history.some(h => h.includes("ss")) },
      { title: "Мониторинг",
        desc: "Создай `monitor.sh` с командой `df -h`",
        hint: "vim monitor.sh",
        check: sh => ["/home/user/monitor.sh", "/home/user/projects/monitor.sh"].some(p => fileContains(sh.fs, p, "df")) },
      { title: "Сервис",
        desc: "Проверь сервис: `systemctl status myapp`",
        hint: "systemctl status myapp",
        check: sh => sh.history.some(h => h.includes("systemctl status")) },
      { title: "Архив",
        desc: "Создай gzip-архив логов: `tar -czf logs.tar.gz /var/log`",
        hint: "tar -czf logs.tar.gz /var/log",
        check: sh => sh.history.some(h => h.includes("tar") && h.includes("logs")) },
      { title: "Бэкап",
        desc: "Сделай копию passwd: `cp /etc/passwd ~/passwd.bak`",
        hint: "cp /etc/passwd ~/passwd.bak",
        check: sh => fileExists(sh.fs, "/home/user/passwd.bak") },
    ]},
];